language: node_js
node_js:
  - '10'
before_script:
  - rm package-lock.json
script: 
  - npm install
  - npm install coveralls --save-dev
  - npm test
after_success:
  - cat ./jest-coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -v
notifications:
  on_success: never
  on_failure: always
